/**
 * Header manifests for the team screen views, from Knowledge Base › Import contract ›
 * Header manifest. Columns are listed in export order. A view that OOTP has changed keeps
 * every version, oldest first; the last one is the current export. The league sortable
 * files reuse these headers.
 */

export type Side = 'hitters' | 'pitchers';

export interface ViewManifest {
  /** The side whose players the view lists. */
  readonly side: Side;
  /** Column lists, oldest first; the last is the current export. */
  readonly versions: readonly (readonly string[])[];
}

/** An older export: the current columns minus the ones a later version added. */
const without = (columns: readonly string[], added: readonly string[]) =>
  columns.filter((column) => !added.includes(column));

const BATTING_SUPERSTATS_1_V2 = [
  'POS',
  'Name',
  'Inf',
  'TM',
  'LG',
  'BIP',
  'GB/FB',
  'LD%',
  'GB%',
  'FB%',
  'IFFB',
  'HR/FB',
  'IFH%',
  'BUH%',
  'Pull%',
  'Cent%',
  'Oppo%',
  'Soft%',
  'Avg%',
  'Solid%',
  'EV',
  'mEV',
  'LA',
  'BAR',
  'BAR%',
  'HHi',
  'HHi%',
  'xBACON',
  'xSLGCON',
  'xwOBACON',
  'xBA',
  'xSLG',
  'xwOBA',
] as const;

const PITCHING_SUPERSTATS_1_V2 = [
  'POS',
  'Name',
  'G',
  'GS',
  'BIP',
  'GB/FB',
  'LD%',
  'GB%',
  'FB%',
  'IFFB',
  'HR/FB',
  'Soft%',
  'Med%',
  'Solid%',
  'EV',
  'mEV',
  'BAR%',
  'HHi%',
  'xBACON',
  'xSLGCON',
  'xwOBACON',
  'xBA',
  'xSLG',
  'xwOBA',
  'xERA',
] as const;

const PITCHING_SUPERSTATS_2_V2 = [
  'POS',
  'Name',
  'G',
  'GS',
  'PI',
  'SW',
  'WH',
  'OSW',
  'CH',
  'OS%',
  'ZS%',
  'SW%',
  'OC%',
  'ZC%',
  'CTC%',
  'Z%',
  'WH%',
  'CH%',
  'CL%',
  'RV-FB',
  'RV-BR',
  'RV-OFF',
  'RV',
] as const;

export const VIEW_MANIFESTS = {
  default: {
    side: 'hitters',
    versions: [
      [
        'POS',
        '#',
        'Name',
        'Inf',
        'Mor',
        'Age',
        'NAT',
        'HT',
        'WT',
        'B',
        'T',
        'OVR',
        'POT',
        'SLR',
        'YL',
        'MLY',
        'SctAcc',
      ],
    ],
  },
  batting_stats_1: {
    side: 'hitters',
    versions: [
      [
        'POS',
        '#',
        'Name',
        'Inf',
        'B',
        'T',
        'G',
        'PA',
        'AB',
        'H',
        '2B',
        '3B',
        'HR',
        'RBI',
        'R',
        'BB',
        'IBB',
        'HP',
        'K',
        'GIDP',
        'AVG',
        'OBP',
        'SLG',
        'ISO',
        'OPS',
        'OPS+',
        'BABIP',
        'WAR',
        'SB',
        'CS',
      ],
    ],
  },
  batting_stats_2: {
    side: 'hitters',
    versions: [
      [
        'POS',
        '#',
        'Name',
        'Inf',
        'B',
        'T',
        'G',
        'PA',
        'BB',
        'BB%',
        'SH',
        'SF',
        'CI',
        'K',
        'K%',
        'GIDP',
        'EBH',
        'TB',
        'RC',
        'RC/27',
        'ISO',
        'wOBA',
        'WPA',
        'PI/PA',
        'UBR',
      ],
    ],
  },
  batting_superstats_1: {
    side: 'hitters',
    versions: [
      without(BATTING_SUPERSTATS_1_V2, ['xBACON', 'xSLGCON', 'xwOBACON']),
      BATTING_SUPERSTATS_1_V2,
    ],
  },
  batting_superstats_2: {
    side: 'hitters',
    versions: [
      [
        'POS',
        'Name',
        'Inf',
        'TM',
        'LG',
        'PI',
        'WH%',
        'CH%',
        'Z%',
        'CL%',
        'OS%',
        'ZS%',
        'SW%',
        'OC%',
        'ZC%',
        'CTC%',
        'FF%',
        'BR%',
        'OFF%',
        'RV-FB',
        'RV-BR',
        'RV-OFF',
        'RV',
      ],
    ],
  },
  custom_bat_pot: {
    side: 'hitters',
    versions: [
      [
        'POS',
        'Name',
        'B',
        'T',
        'WE',
        'INT',
        'CON P',
        'HT P',
        'K P',
        'GAP P',
        'POW P',
        'EYE P',
        'BUN',
        'BFH',
        'BBT',
        'GBT',
        'FBT',
        'C ABI',
        'C FRM',
        'C ARM',
        'IF RNG',
        'IF ERR',
        'IF ARM',
        'TDP',
        'OF RNG',
        'OF ERR',
        'OF ARM',
        'SPE',
        'STE',
        'SR',
        'RUN',
        'DEF',
        'Risk',
      ],
    ],
  },
  pitching_stats_1: {
    side: 'pitchers',
    versions: [
      [
        'POS',
        '#',
        'Name',
        'Inf',
        'B',
        'T',
        'G',
        'GS',
        'W',
        'L',
        'SV',
        'HLD',
        'IP',
        'HA',
        'HR',
        'R',
        'ER',
        'BB',
        'K',
        'HP',
        'ERA',
        'AVG',
        'BABIP',
        'WHIP',
        'HR/9',
        'BB/9',
        'K/9',
        'K/BB',
        'ERA+',
        'FIP',
        'WAR',
      ],
    ],
  },
  pitching_stats_2: {
    side: 'pitchers',
    versions: [
      [
        'POS',
        '#',
        'Name',
        'Inf',
        'B',
        'T',
        'G',
        'WIN%',
        'SV%',
        'BS',
        'SD',
        'MD',
        'IP',
        'BF',
        'DP',
        'RA',
        'GF',
        'IR',
        'IRS%',
        'pLi',
        'QS',
        'QS%',
        'CG',
        'CG%',
        'SHO',
        'PPG',
        'RSG',
        'GO%',
        'SIERA',
        'SB',
        'CS',
        'WPA',
      ],
    ],
  },
  pitching_superstats_1: {
    side: 'pitchers',
    versions: [
      without(PITCHING_SUPERSTATS_1_V2, ['mEV', 'BAR%', 'HHi%', 'xBACON', 'xSLGCON', 'xwOBACON']),
      PITCHING_SUPERSTATS_1_V2,
    ],
  },
  pitching_superstats_2: {
    side: 'pitchers',
    versions: [without(PITCHING_SUPERSTATS_2_V2, ['OSW', 'CTC%']), PITCHING_SUPERSTATS_2_V2],
  },
  cus_pitch_pot: {
    side: 'pitchers',
    versions: [
      [
        'POS',
        'Name',
        'Age',
        'T',
        'WE',
        'INT',
        'STU P',
        'MOV P',
        'HRA P',
        'PBABIP P',
        'CON P',
        'VELO',
        'STM',
        'VT',
        'Slot',
        'PT',
        'G/F',
        'HLD',
        'DEF Pot',
        'Risk',
      ],
    ],
  },
} as const satisfies Record<string, ViewManifest>;

export type ViewId = keyof typeof VIEW_MANIFESTS;
